export const blogs = [
  {
    title: "Next.js Middleware",
    description: "A Modern Way to Control Requests and Responses",
    icon: "nextjs.svg",
    date: "25-10-24",
    link: "/next-js-middleware",
    bgColor: "from-pink-500 to-blue-500",
    darkBgColor: "dark:from-pink-600 dark:to-blue-600",
  },
  {
    title: "What Are Types and Interfaces?",
    description:
      "Understanding Types vs. Interfaces in TypeScript for React Projects",
    icon: "ts.svg",
    date: "25-10-24",
    link: "/types-vs-interfaces",
    bgColor: "from-blue-500 to-green-500",
    darkBgColor: "dark:from-blue-600 dark:to-green-600",
  },
  //   {
  //     title: "Next.js Middleware",
  //     description: "A Modern Way to Control Requests and Responses",
  //     icon: "nextjs.svg",
  //     date: "25-10-2024",
  //     link: "/next-js-middleware",
  //     bgColor: "from-yellow-500 to-blue-500",
  //     darkBgColor: "dark:from-yellow-600 dark:to-blue-600",
  //   },
  //   {
  //     title: "Next.js Middleware",
  //     description: "A Modern Way to Control Requests and Responses",
  //     icon: "nextjs.svg",
  //     date: "25-10-2024",
  //     link: "/next-js-middleware",
  //     bgColor: "from-purple-500 via-pink-500 to-red-500",
  //     darkBgColor: "dark:from-purple-600 dark:via-pink-600 dark:to-red-600",
  //   },
  //   {
  //     title: "Next.js Middleware",
  //     description: "A Modern Way to Control Requests and Responses",
  //     icon: "nextjs.svg",
  //     date: "25-10-2024",
  //     link: "/next-js-middleware",
  //     bgColor: "from-red-500 via-orange-500 to-yellow-500",
  //     darkBgColor: "dark:from-red-600 dark:via-orange-600 dark:to-yellow-600",
  //   },
  //   {
  //     title: "Next.js Middleware",
  //     description: "A Modern Way to Control Requests and Responses",
  //     icon: "nextjs.svg",
  //     date: "25-10-2024",
  //     link: "/next-js-middleware",
  //     bgColor: "from-green-500 via-teal-500 to-blue-500",
  //     darkBgColor: "dark:from-green-600 dark:via-teal-600 dark:to-blue-600",
  //   },
  //   {
  //     title: "Next.js Middleware",
  //     description: "A Modern Way to Control Requests and Responses",
  //     icon: "nextjs.svg",
  //     date: "25-10-2024",
  //     link: "/next-js-middleware",
  //     bgColor: "from-blue-500 via-indigo-500 to-purple-500",
  //     darkBgColor: "dark:from-blue-600 dark:via-indigo-600 dark:to-purple-600",
  //   },
  //   {
  //     title: "Next.js Middleware",
  //     description: "A Modern Way to Control Requests and Responses",
  //     icon: "nextjs.svg",
  //     date: "25-10-2024",
  //     link: "/next-js-middleware",
  //     bgColor: "from-yellow-500 via-green-500 to-teal-500",
  //     darkBgColor: "dark:from-yellow-600 dark:via-green-600 dark:to-teal-600",
  //   },
];
